//===- double_buffered.mlir ------------------------------------*- MLIR -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-lower-memtile-row-stores %s | FileCheck %s

module {
  aie.device(xcve2302) {
    %mem = aie.tile(2, 1)
    %core = aie.tile(2, 2)

    aie.memtile_row_store @row_store0(%core, %mem) {part_count = 2 : i32, buffer_count = 2 : i32} : memref<32x96xbf16>

    aie.core(%core) {
      %src = aie.memtile_row_store.acquire @row_store0(Produce) : memref<32x96xbf16>
      aie.memtile_row_store.release @row_store0(Produce)
      %dst = aie.memtile_row_store.acquire @row_store0(Consume) : memref<32x96xbf16>
      aie.memtile_row_store.release @row_store0(Consume)
      aie.end
    }
  }
}

// CHECK-LABEL: module {
// CHECK: aie.device(xcve2302) {
// CHECK: %[[MEM:.*]] = aie.tile(2, 1)
// CHECK: %[[CORE:.*]] = aie.tile(2, 2)
// CHECK-NOT: aie.memtile_row_store
// CHECK-DAG: %[[SRC:.*]] = aie.buffer(%[[CORE]]) {sym_name = "row_store0_src"} : memref<32x96xbf16>
// CHECK-DAG: %[[DST:.*]] = aie.buffer(%[[CORE]]) {sym_name = "row_store0_dst"} : memref<32x96xbf16>
// CHECK-DAG: %[[ROW0:.*]] = aie.buffer(%[[MEM]]) {sym_name = "row_store0_row_0"} : memref<6144xbf16>
// CHECK-DAG: %[[ROW1:.*]] = aie.buffer(%[[MEM]]) {sym_name = "row_store0_row_1"} : memref<6144xbf16>
// CHECK-DAG: %[[ROW0_EMPTY:.*]] = aie.lock(%[[MEM]]) {init = 1 : i32, sym_name = "row_store0_row_0_empty"}
// CHECK-DAG: %[[ROW0_FULL:.*]] = aie.lock(%[[MEM]]) {init = 0 : i32, sym_name = "row_store0_row_0_full"}
// CHECK-DAG: %[[ROW1_EMPTY:.*]] = aie.lock(%[[MEM]]) {init = 1 : i32, sym_name = "row_store0_row_1_empty"}
// CHECK-DAG: %[[ROW1_FULL:.*]] = aie.lock(%[[MEM]]) {init = 0 : i32, sym_name = "row_store0_row_1_full"}
// CHECK: aie.memtile_dma(%[[MEM]]) {
// CHECK: aie.dma_start(S2MM, 0
// CHECK: aie.use_lock(%[[ROW0_EMPTY]], AcquireGreaterEqual, 1)
// CHECK: aie.dma_bd(%[[ROW0]] : memref<6144xbf16>, 0, 6144)
// CHECK: aie.use_lock(%[[ROW0_FULL]], Release, 1)
// CHECK: aie.use_lock(%[[ROW1_EMPTY]], AcquireGreaterEqual, 1)
// CHECK: aie.dma_bd(%[[ROW1]] : memref<6144xbf16>, 0, 6144)
// CHECK: aie.use_lock(%[[ROW1_FULL]], Release, 1)
// CHECK: aie.dma_start(MM2S, 1
// CHECK: aie.use_lock(%[[ROW0_FULL]], AcquireGreaterEqual, 1)
// CHECK: aie.dma_bd(%[[ROW0]] : memref<6144xbf16>, 0, 6144)
// CHECK: aie.use_lock(%[[ROW0_EMPTY]], Release, 1)
// CHECK: aie.use_lock(%[[ROW1_FULL]], AcquireGreaterEqual, 1)
// CHECK: aie.dma_bd(%[[ROW1]] : memref<6144xbf16>, 0, 6144)
// CHECK: aie.use_lock(%[[ROW1_EMPTY]], Release, 1)
